// packages/cli/src/commands/inject.ts
// ─────────────────────────────────────────────────────────────
// robrain inject [--query TEXT] [--files file1,file2] [--copy]
//
// Queries the local decision store and returns a formatted
// context string the developer can paste into Claude Code.
//
// This is the manual retrieval path for OSS self-hosted users.
// The Rory Plans cloud version does this automatically at every
// task boundary via the Control MCP — no paste needed.
// ─────────────────────────────────────────────────────────────

import chalk   from 'chalk'
import ora     from 'ora'
import { readConfig, isAuthenticated } from '../lib/config.js'
import { gatherProjectInfo }           from '../lib/project.js'
import { cwd }                         from 'process'
import { execSync }                    from 'child_process'

interface InjectOptions {
  query?:  string    // semantic query to find relevant memories
  files?:  string    // comma-separated file paths in scope
  copy?:   boolean   // copy output to clipboard
  limit?:  number    // max memories to include (default 5)
  all?:    boolean   // show all matching, not just top-scored
}

export async function injectCommand(opts: InjectOptions): Promise<void> {
  console.log()

  const config  = readConfig()
  const info    = gatherProjectInfo(cwd())

  // Determine perception URL — local self-hosted or Rory Plans
  const percUrl = config.perceptionUrl ?? 'http://localhost:3001'
  const percKey = config.perceptionKey ?? ''

  // ── Build query ────────────────────────────────────────────
  // If no query provided, use recent decisions
  const query   = opts.query
  const files   = opts.files ? opts.files.split(',').map(f => f.trim()) : []
  const limit   = opts.limit ?? 5

  const spinner = ora({ text: 'Fetching relevant decisions...', color: 'green' }).start()

  let decisions: Array<{
    id:             string
    decision:       string
    rationale:      string | null
    rejected:       Array<{ option: string; reason: string }>
    files_affected: string[]
    confidence:     number
    scope:          string
    created_at:     string
    similarity?:    number
  }> = []

  try {
    // Build query params
    const params = new URLSearchParams({
      project_id: info.id,
      limit:      String(limit),
    })
    if (query)  params.set('query', query)
    if (!query) params.set('recent', 'true')

    const res = await fetch(`${percUrl}/decisions?${params}`, {
      headers: percKey ? { 'Authorization': `Bearer ${percKey}` } : {},
    })

    if (!res.ok) {
      spinner.fail(`Could not fetch decisions (${res.status}). Is Perception running?`)
      console.log(chalk.dim(`  Expected at: ${percUrl}`))
      console.log(chalk.dim('  Start with: pnpm docker:up\n'))
      process.exit(1)
    }

    const data = await res.json() as { decisions: typeof decisions }
    decisions  = data.decisions ?? []

    // If files provided, boost file-overlapping decisions to top
    if (files.length > 0) {
      decisions.sort((a, b) => {
        const aOverlap = a.files_affected.filter(f => files.some(fi => f.includes(fi))).length
        const bOverlap = b.files_affected.filter(f => files.some(fi => f.includes(fi))).length
        return bOverlap - aOverlap || (b.similarity ?? 0) - (a.similarity ?? 0)
      })
    }

  } catch (err) {
    spinner.fail('Could not reach Perception API')
    console.log(chalk.dim(`\n  Make sure Perception is running: pnpm docker:up\n`))
    process.exit(1)
  }

  spinner.stop()

  if (decisions.length === 0) {
    console.log(chalk.dim(`  No decisions found for "${query ?? 'recent'}"\n`))
    console.log(chalk.dim('  Run a Claude Code session first to capture decisions.\n'))
    return
  }

  // ── Format context string ──────────────────────────────────
  const lines: string[] = [
    `[RoBrain context — ${info.name}${query ? ` — "${query}"` : ' — recent decisions'}]`,
  ]

  for (const d of decisions) {
    const date   = new Date(d.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
    const conf   = d.confidence >= 0.9 ? 'high' : d.confidence >= 0.6 ? 'medium' : 'low'
    const vetoes = (d.rejected ?? []).map(r => `${r.option} (${r.reason})`).join(' over ')
    const vetoStr = vetoes ? ` over ${vetoes}` : ''
    const rationale = d.rationale ? ` — ${d.rationale}` : ''

    lines.push(`• Chose ${d.decision}${vetoStr}${rationale} [${date}, ${conf} confidence]`)
  }

  // Cloud upgrade note (for OSS users)
  lines.push('')
  lines.push('— Generated by RoBrain OSS. Upgrade to Rory Plans for automatic injection.')

  const output = lines.join('\n')

  // ── Display ────────────────────────────────────────────────
  console.log(chalk.bold(`  Context for: ${info.name}`))
  console.log(chalk.dim(`  ${decisions.length} decision${decisions.length === 1 ? '' : 's'} found\n`))
  console.log(chalk.dim('  ─────────────────────────────────────'))
  console.log()
  console.log(output)
  console.log()
  console.log(chalk.dim('  ─────────────────────────────────────'))
  console.log()

  // ── Copy to clipboard ──────────────────────────────────────
  if (opts.copy) {
    try {
      const cmd = process.platform === 'darwin' ? 'pbcopy'
                : process.platform === 'win32'  ? 'clip'
                : 'xclip -selection clipboard'
      execSync(cmd, { input: output })
      console.log(chalk.green('  ✓ Copied to clipboard — paste into Claude Code\n'))
    } catch {
      console.log(chalk.yellow('  Could not copy to clipboard automatically.'))
      console.log(chalk.dim('  Copy the text above and paste it into Claude Code.\n'))
    }
  } else {
    console.log(chalk.dim('  Tip: add --copy to copy this directly to your clipboard'))
    console.log(chalk.dim('  Tip: add --query "auth decisions" to search for specific context'))
    console.log()
    console.log(chalk.dim('  Want automatic injection without pasting?'))
    console.log(chalk.dim('  → ') + chalk.cyan('roryplans.ai') + chalk.dim(' — Control MCP injects at every task boundary\n'))
  }
}
